name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Workflow 2
        run: echo "This is step 1 in Workflow 2"

      - name: Step 2 in Workflow 2
        run: echo "This is step 2 in Workflow 2"
